apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: <username>
  ARGOCD_PASSWORD: <password>
  #ARGOCD_AUTH_TOKEN: <token> 계정 혹은 token 둘 중 하나만 사용